### ISSUE TITLE
could not execute massdns: exit status 2

### ISSUE THREAD

**Issue by prasgop** [projectdiscovery/shuffledns#293]
Shuffledns is throwing the below massdns error. I have tried to add -massdns /usr/local/bin/massdns (binary location) after seeing comments under a similar issue posted here but it's not helping either. I have installed both massdns and shuffledns today only (using go isntall for the later) so they are supposedly the latest ones. 

![ss](https://github.com/projectdiscovery/shuffledns/assets/116869728/8731d7c2-20ca-4bd7-96fa-594831240670)

**Comment by Mzack9999** [comment]
@prasgop from https://github.com/blechschmidt/massdns/issues/151 it seems like you were able to fix the issue (from the thread it seems it was due to an unexpected space in the argument supplied for the -t parameter). I'm closing the issue since no action is required. Feel free to reopen if needed. Thanks!
